# Generated by Django 3.1.5 on 2021-01-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "profile", "verbose_name_plural": "profiles"},
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="photo",
            new_name="profile_photo",
        ),
    ]
