# Generated by Django 3.1.5 on 2021-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210114_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="edit_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="localization",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
