# Generated by Django 3.1.5 on 2021-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210114_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
