# Generated by Django 3.1.5 on 2021-01-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
